/* eslint-disable @next/next/no-script-component-in-head */
import "../styles/globals.css";
import "antd/dist/antd.css";
import Head from "next/head";
import Script from "next/script";
import MasterLayout from "../components/master-layout/MasterLayout";
import { useRouter } from "next/router";
import { routesWithoutMasterLayout } from "../util/constant";
import { useEffect } from "react";
import Auth from "../util/auth";

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  useEffect(() => {
    sessionOut();
  },[]);
  const sessionOut = () => {
    // let sec = 28800;
    //   let hour = parseInt(sec / 3600);
    //   const result1 = addHours(new Date(), hour);
      setInterval(() => {
        Auth.removeToken();
        window.open("/login", "_self");
      }, 18000000);
  };
  return (
    <>
      <Head>
        <script
          async
          defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCsvXDft5BRwE1TiqtbFHyX2xoKWE3EC1c&libraries=places"
        ></script>
        <title>Z-Lite</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=0"
        />
        <link rel="icon" href="/zlite_logo.png" />
      </Head>
      {routesWithoutMasterLayout.includes(router.pathname) ? (
        <Component {...pageProps} />
      ) : (
        <MasterLayout content={<Component {...pageProps} />} />
      )}
    </>
  );
}

export default MyApp;
